name: '${name}'
version: '${version}'
author: '${author}'
website: '${website}'
description: '\nA plugin that handles Delta-UHC\n'

main: us.jcedeno.deltauhc.bukkit.DeltaUHC

api-version: 1.21
depend: [VoidGen]