# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Gradle build and upload artifacts

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    # Setup Java 17
    - name: Set up JDK 17
      uses: actions/setup-java@v1
      with:
        java-version: 17
    # Setup caching to make it faster
    - name: Cache Gradle packages
      uses: actions/cache@v2
      with:
        path: ~/.gradle/caches
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle') }}
        restore-keys: ${{ runner.os }}-gradle
    # Make gradlew executable
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    
    # Pull the gradle.properties from the repo secrets
    - name: Restore gradle.properties
      env:
        GRADLE_PROPERTIES: ${{ secrets.GRADLE_PROPERTIES }}
      shell: bash
      run: |
        mkdir -p ~/.gradle/
        cat >> ~/.gradle/gradle.properties << EOL
        ${GRADLE_PROPERTIES}
        EOL
    # Build the project
    - name: Build with Gradle
      run: ./gradlew :bukkit:clean :bukkit:build :bukkit:test 
    # Publish to maven repository
    - name: Build with Gradle
      run: ./gradlew publish
    # Upload artifacts
    - uses: actions/upload-artifact@v2
      with:
        name: monad-uhc-jdk-17
        path: bukkit/build/libs/folia-bundler-*.jar
